spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: train
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa.show-sql: true
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa.hibernate.ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  main:
    allow-bean-definition-overriding: true
server:
  servlet:
    session:
      timeout: 15m
logging:
  level:
    org:
      springframework: DEBUG
