spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: train
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa.hibernate.ddl-auto: create